version: '3.8'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_HOST: db
  DATABASE_PORT: 5432
  DATABASE_USERNAME: vapor
  DATABASE_PASSWORD: password
  DATABASE_NAME: vapor

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: vapor
      POSTGRES_USER: vapor
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: grocery-app-server:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    ports:
      - '8080:8080'
    depends_on:
      - db
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]

volumes:
  pgdata:
